### ISSUE TITLE
Build not working anymore

### ISSUE THREAD

**Issue by feliwir** [bazelbuild/rules_foreign_cc#160]
Hey, since the latest master i am getting this error:
``` 
ERROR: error loading package '': Extension file not found. Unable to load package for '//tools/build_defs:version.bzl': BUILD file not found on package path
```

My setup is identical to the one described in ReadMe.md. I am running on Bazel 19.2

**Comment by feliwir** [comment]
Hey @irengrig,
there really isn't more to the output unfortunaly. I am running on Ubuntu 18.10. The WORKSPACE looks like this:
```sh
workspace(name = "camd")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Group the sources of the library so that CMake rule have access to it
all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

# Rule repository
http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-master",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

# Workspace initialization function; includes repositories needed by rules_foreign_cc,
# and creates some utilities for the host operating system
rules_foreign_cc_dependencies()

# https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive
http_archive(
  name = "dcmtk",	# Reference as @rule unique name//:target-lib
  build_file_content = all_content,
  urls = ["https://github.com/DCMTK/dcmtk/archive/DCMTK-3.6.3.tar.gz"],
  strip_prefix = "DCMTK-3.6.3"
)
```
and the BUILD like this:
```sh
load("@rules_foreign_cc//tools/build_defs:cmake.bzl", "cmake_external")

cmake_external(
   name = "dcmtk",

   lib_source = "@dcmtk//:all",

   # We are selecting the resulting static library to be passed in C/C++ provider
   # as the result of the build;
   # However, the cmake_external dependants could use other artefacts provided by the build,
   # according to their CMake script
   static_libraries = ["libdcmtk.a"],
)
```

I run the bazel command like this: 
`
bazel build --experimental_cc_skylark_api_enabled_packages=@rules_foreign_cc//tools/build_defs,tools/build_defs ...
`

**Comment by irengrig** [comment]
Fixed. Sorry for that.

Please also modify the value of the command line flag to be: `bazel build --experimental_cc_skylark_api_enabled_packages=@rules_foreign_cc//tools/build_defs,tools/build_defs,@foreign_cc_impl// ...`, i.e. `@foreign_cc_impl` needs to be added.

I also noticed that in your example, the strip_prefix should be "dcmtk-DCMTK-3.6.3",
and it does not build for me because I am missing some of the local dependencies:
`-- Looking for main in socket
-- Looking for main in socket - not found
-- Looking for socket in socket
-- Looking for socket in socket - not found
-- Configuring incomplete, errors occurred!
`

**Comment by feliwir** [comment]
Thanks for the quick fix! Yeah i didn't get to the build stage yet, so i'll try to figure that out now

**Comment by feliwir** [comment]
Okay, tried again and it's still not working:
```
ERROR: error loading package '': Extension file not found. Unable to load package for '//tools/build_defs:run_shell_file_utils.bzl': BUILD file not found on package path
```

Not sure what is different in my setup to yours.

**Comment by irengrig** [comment]
Please try running bazel clean --expunge and then the build.
The reference is [fixed](https://github.com/bazelbuild/rules_foreign_cc/blob/59bd073a228a16e3fedc12eab9bc7c9ed0481da6/tools/build_defs/old_10_2018/framework.bzl#L16), so for now I do not understand the reason...

**Comment by irengrig** [comment]
> Thanks it seems like the --expunge made the difference
Nice!

> On another note: I am getting the same error during configuration as you get. The temporary log files that get generated don't exist in the specified path (e.g. /tmp/tmp.umU5TOws6c/CMakeFiles/CMakeError.log )

Yep, that's because I build in the temp directory which gets deleted by the script: https://github.com/bazelbuild/rules_foreign_cc/blob/59bd073a228a16e3fedc12eab9bc7c9ed0481da6/tools/build_defs/old_10_2018/framework.bzl#L249
In principle, you can git clone to the local directory, use local_repository to the locations, and comment this line out.

That is a good idea to provide such information, I filed a feature issue to track: https://github.com/bazelbuild/rules_foreign_cc/issues/162

**Comment by irengrig** [comment]
Please see #162; temp directory (and dependencies directory if --sandbox_debug is passed) will be kept in case of cmake_external failure.

**Comment by feliwir** [comment]
@irengrig hey i looked at the logs by now. It seems to fail during configuration stage, eventhough it doesn't fail outside of bazel (when i configure the same source by hand). Any idea what might cause this? I could paste the cmakerror.log here, but it doesn't tell much except that some checks fail etc.

**Comment by irengrig** [comment]
Yes, please copy the output, logs and the target you are invoking here.
This will help to understand the problem.

**Comment by feliwir** [comment]
I pasted all logs in this gist:
https://gist.github.com/feliwir/1ebf92f9764ce499899b92fbdf1df850

I think the error is in the stdout.txt to be honest:
```
ERROR: /home/stephan/Development/camd_2/BUILD:3:1: error executing shell command: '/bin/bash -c echo "
```

**Comment by irengrig** [comment]
From what I see in the logs, CMake can not find some headers, for instance: 

Determining if the include file fstream.h exists failed with the following output:
Change Dir: /tmp/tmp.nFc1YUQBgK/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_24b74/fast"
/usr/bin/make -f CMakeFiles/cmTC_24b74.dir/build.make CMakeFiles/cmTC_24b74.dir/build
make[1]: Entering directory '/tmp/tmp.nFc1YUQBgK/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_24b74.dir/CheckIncludeFile.cxx.o
/usr/bin/gcc    -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++0x -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -D_XOPEN_SOURCE_EXTENDED -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_BSD_COMPAT -D_OSF_SOURCE -D_POSIX_C_SOURCE=199506L  -O3 -DNDEBUG   -o CMakeFiles/cmTC_24b74.dir/CheckIncludeFile.cxx.o -c /tmp/tmp.nFc1YUQBgK/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
/tmp/tmp.nFc1YUQBgK/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:10: fatal error: fstream.h: No such file or directory
 #include <fstream.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_24b74.dir/build.make:66: CMakeFiles/cmTC_24b74.dir/CheckIncludeFile.cxx.o] Error 1
make[1]: Leaving directory '/tmp/tmp.nFc1YUQBgK/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_24b74/fast] Error 2

Also, in the review CMake produces:

-- Looking for C++ include fstream
-- Looking for C++ include fstream - found
-- Looking for C++ include fstream.h
-- Looking for C++ include fstream.h - not found

**Comment by feliwir** [comment]
Well, those do definitely exist though
