### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_foreign_cc#472]
Same task as https://github.com/bazelbuild/bazel/issues/12200 with the same justification 😄 

It would mean a lot to see this get done.

**Comment by attilaolah** [comment]
Probably should not be too much trouble. What happens to existing pull requests though?

**Comment by UebelAndre** [comment]
If we rename the branch through github then all PRs are automatically updated. Users will have to fix their forks though which I'm not sure if there's a way to do that by renaming it as well but it's easy enough to fetch upstream and just start using `main`. That's what I ended up doing when `rules_rust` renamed it's branch.

**Comment by UebelAndre** [comment]
@philwo I'd like to do this sometime soon but I'm told for https://github.com/bazelbuild/rules_rust/issues/445 you were pinged to update CI? Can I coordinate a day where I can rename the branch and you update CI 🙏

**Comment by philwo** [comment]
@UebelAndre Feel free to go ahead and ping me here, I can make the changes immediately then :)

**Comment by UebelAndre** [comment]
The branch has been renamed. Users with forks should be able to rename the branch through github (most people should see a notification about this)

<img width="537" alt="Screen Shot 2021-02-12 at 8 46 11 AM" src="https://user-images.githubusercontent.com/26427366/107796607-ea220580-6d0e-11eb-95eb-23928a88efc8.png">


To update your local environment, run:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

@philwo Hey, just updated the branch name. Can you update CI for us as well 🙏

**Comment by jonmeow** [comment]
Instructions in the README say:
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",

Did renaming master to main break all uses of this?

**Comment by UebelAndre** [comment]
Ah yes, good call out, thank you. I'd planned to replace this with a release (that we also plan to ship soon) but I'll go fix that real quick.

**Comment by UebelAndre** [comment]
> Instructions in the README say:
> url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
> 
> Did renaming master to main break all uses of this?

@jonmeow This has been fixed now. Thanks again!

**Comment by jonmeow** [comment]
It looks like https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip is still a 404, so a reference like https://github.com/google/mediapipe/blob/master/WORKSPACE#L42 is still broken. Is that intended, that adopters will need to update their references?

(I don't know what bazel would support as far as alternatives for this, maybe provide a master branch that continues to mirror main, with a warning to migrate?)

**Comment by UebelAndre** [comment]
@jonmeow Ah, I understand what you're saying now. I've created the `master` branch again to restore this url. This branch will not receive any more updates though. I'd recommend updating your projects.

**Comment by UebelAndre** [comment]
> (I don't know what bazel would support as far as alternatives for this, maybe provide a master branch that continues to mirror main, with a warning to migrate?)

Some additional details here. I don't believe it's good practice to rely on a changing url like this. Best practice is to pin to a commit and only update when you have to. By relying on an active branch like `main`, you're exposing yourself to random cache invalidation as new commits are made here.

I can look into adding a warning to that branch though. Hopefully when we roll out releases, updating will be easier and more streamline for everyone.

**Comment by jonmeow** [comment]
> > (I don't know what bazel would support as far as alternatives for this, maybe provide a master branch that continues to mirror main, with a warning to migrate?)
> 
> Some additional details here. I don't believe it's good practice to rely on a changing url like this. Best practice is to pin to a commit and only update when you have to. By relying on an active branch like `main`, you're exposing yourself to random cache invalidation as new commits are made here.

I agree, we've switched to `main` and I'm already thinking about pinning -- that was just a quick fix. Maybe update the README to advise pinning to future-proof?

> I can look into adding a warning to that branch though. Hopefully when we roll out releases, updating will be easier and more streamline for everyone.

SGTM

**Comment by UebelAndre** [comment]
> I agree, we've switched to `main` and I'm already thinking about pinning -- that was just a quick fix. Maybe update the README to advise pinning to future-proof?

I added a `print` warning to `master`. Hopefully others shouldn't run into the same issues now. Sorry for the inconvenience and thanks for pinging this issue! 🙏

**Comment by jonmeow** [comment]
Thanks for the fixes. :)

**Comment by UebelAndre** [comment]
With CI now running on `main`, this issue can be closed
https://buildkite.com/bazel/rules-foreign-cc/builds/1671

**Comment by UebelAndre** [comment]
Closing this now that everything has been updated.

**Comment by UebelAndre** [comment]
With now having updated docs to inform users on how to download the rules more efficiently, the `master` branch will soon be, once again, deleted. Please migrate to a release should you run into issues as a result.

**Comment by EJTTianYu** [comment]
Hi, seems the https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip has been closed.

I used this url before, which release match the branch before it was deleted, thanks

**Comment by UebelAndre** [comment]
The matching pin for the `master` branch would be
```python
http_archive(
    name = "rules_foreign_cc",
    sha256 = "0e2f05c8bffb87f043dbab5e326a41852ed53d2e6e7bbb74e5f36e66624d3e26"
    strip_prefix = "rules_foreign_cc-80143e7c5af752acc65df783d94f94a02cf11399",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/80143e7c5af752acc65df783d94f94a02cf11399.tar.gz",
)
```
Which is before to release `0.1.0`.
